update error function

diff --git a/archboot b/archboot
--- a/archboot
+++ b/archboot
@@ -56,7 +56,7 @@ _note() {
 
 # Function to display errors
 _error() {
-    echo -e "$red\nError: $yellow$1$nc\n" >&2
+    echo -e "$red\n\nError: $yellow$1$nc\n" >&2
     for d in $(seq 5 -1 1)
     do
         echo -ne "\r\033[K${green}System will reboot in ${d}s...$nc" && sleep 1
