Rebuild code for better bash ident

diff --git a/archboot b/archboot
--- a/archboot
+++ b/archboot
@@ -1,20 +1,20 @@
 #!/bin/bash
-__appname__="archboot"
-__version__="v2.9.0"
-__branch__="dev"
-__author__="grm34"
-__license__="Apache License 2.0"
+APPNAME="archboot"
+VERSION="v2.9.0"
+BRANCH="dev"
+AUTHOR="grm34"
+LICENSE="Apache License 2.0"
 
 _archboot_banner() {
-    echo -e """${red}
+    echo -e """${RED}
       _             _     _                 _
      / \   _ __  __| |__ | |__   ___   ___ | |_
     / _ \ | '__/ __| '_ \| '_ \ / _ \ / _ \| __|
    / ___ \| | | (__| | | | |_) | (_) | (_) | |_
-  /_/   \_\_|  \___|_| |_|_.__/ \___/ \___/ \__|${green}${__version__}
-${blue}
- Welcome in ${__appname__}, a script made with love by ${__author__}
-${nc}
+  /_/   \_\_|  \___|_| |_|_.__/ \___/ \___/ \__|${GREEN}${VERSION}
+${BLUE}
+ Welcome in ${APPNAME}, a script made with love by ${AUTHOR}
+${NC}
 Arch Linux is a light and fast distribution whose concept
 is to remain  as simple  as possible. In the same purpose
 this  script  performs  minimalist  installation, it only
@@ -24,7 +24,7 @@ language, hostname, username, which disk to use, required
 partitions size  and  if  you wish  to install  a desktop
 environment. According to the chosen one  and in order to
 get complete support, additional packages may be required
-For more  information, take a look  at the  ${__appname__} wiki
+For more  information, take a look  at the  ${APPNAME} wiki
 """
 }
 
@@ -38,24 +38,24 @@ For more  information, take a look  at the  ${__appname__} wiki
 # ============================================================================
 
 # Github url for sources and images
-_url=\
-"https://raw.githubusercontent.com/${__author__}/${__appname__}/${__branch__}"
-_gh_pages=\
-"https://raw.githubusercontent.com/${__author__}/${__appname__}/gh-pages"
+URL=\
+"https://raw.githubusercontent.com/${AUTHOR}/${APPNAME}/${BRANCH}"
+GHPAGES=\
+"https://raw.githubusercontent.com/${AUTHOR}/${APPNAME}/gh-pages"
 
 # Shell colors
-red="\e[1;31m"; green="\e[1;32m"; yellow="\e[1;33m"
-blue="\e[1;34m"; cyan="\e[1;36m"; nc="\e[0m"
+RED="\e[1;31m"; GREEN="\e[1;32m"; YELLOW="\e[1;33m"
+BLUE="\e[1;34m"; CYAN="\e[1;36m"; NC="\e[0m"
 
 # Display install steps
 _info() {
-    echo -e "${yellow}\n==> ${cyan}${1}...${nc}"
+    echo -e "${YELLOW}\n==> ${CYAN}${1}...${NC}"
     sleep 2s
 }
 
 # Display some notes
 _note() {
-    echo -e "${red}\nNote: ${blue}${1}${nc}"
+    echo -e "${RED}\nNote: ${BLUE}${1}${NC}"
 }
 
 # Download show progress bar only
@@ -72,38 +72,38 @@ EOF
 
 # Set logfile
 _logs() {
-    _info "Setting ${__appname__} log"
-    datetime=$(date '+%d-%m-%Y')
-    log="${__appname__}-${__version__}_${datetime}.log"
+    _info "Setting ${APPNAME} log"
+    DATETIME=$(date '+%d-%m-%Y')
+    LOG="${APPNAME}-${VERSION}_${DATETIME}.log"
 }
 
 # Set system clock
 _clock() {
     _info "Setting system clock"
     timedatectl set-ntp true
-    timedatectl set-timezone ${timezone}
+    timedatectl set-timezone ${TIMEZONE}
     hwclock --systohc
 }
 
 # Check and return command status
 _check() {
     "$@"
-    local status=$?
-    if [[ ${status} -ne 0 ]]; then
+    local STATUS=$?
+    if [[ ${STATUS} -ne 0 ]]; then
         _error "with ${1}"
     fi
-    return ${status}
+    return ${STATUS}
 }
 
 # Delete sources, umount partitions and exit
 _cleanup() {
-    echo -e "\nCleaning up ${__appname__}..."
-    for source in *; do
-        if [[ ${source} =~ ^(base|bootloader|desktop|display|\
+    echo -e "\nCleaning up ${APPNAME}..."
+    for SOURCE in *; do
+        if [[ ${SOURCE} =~ ^(base|bootloader|desktop|display|\
 firmware|mirrorlist|mounting|partition|user|vga|desktop_apps|\
 display_apps|system_apps|vga_apps|00-keyboard|language|\
 timezone|xprofile|background.png|Grub2-themes)$ ]]; then
-            rm -rf ${source}
+            rm -rf ${SOURCE}
         fi
     done
     df | grep -q /mnt
@@ -120,8 +120,8 @@ trap _cleanup 1 2 3 6
 
 # Reboot with 10s timeout
 _reboot() {
-    for d in $(seq 10 -1 1); do
-        echo -ne "\r\033[K${green}System will reboot in ${d}s...${nc}"
+    for SECOND in $(seq 10 -1 1); do
+        echo -ne "\r\033[K${GREEN}System will reboot in ${SECOND}s...${NC}"
         sleep 1
     done
     reboot
@@ -129,49 +129,49 @@ _reboot() {
 
 # Display error and cleanup
 _error() {
-    echo -e "${red}Error: ${yellow}${1}${nc}\n"
+    echo -e "${RED}Error: ${YELLOW}${1}${NC}\n"
     _cleanup
 }
 
 # Select an option
 _select() {
-    count=0
-    echo -ne "${yellow}\n==> "
-    for entry in ${@}; do
-        echo -ne "${red}[$((++count))] ${green}${entry} ${nc}"
+    COUNT=0
+    echo -ne "${YELLOW}\n==> "
+    for ENTRY in ${@}; do
+        echo -ne "${RED}[$((++COUNT))] ${GREEN}${ENTRY} ${NC}"
     done
-    lenth=${@}
-    number=$((${#*} * 4))
-    count=$((${#lenth} + ${number} + 1))
-    echo -ne "${yellow}\n==> "
+    LENTH=${@}
+    NUMBER=$((${#*} * 4))
+    COUNT=$((${#LENTH} + ${NUMBER} + 1))
+    echo -ne "${YELLOW}\n==> "
     _end
 }
 
 # Ask confirmation (Yes/No)
 _confirm() {
-    count=$((${#1} + 6))
-    until [[ ${confirm} =~ ^(y|n|Y|N|yes|no|Yes|No|YES|NO)$ ]]; do
-        echo -ne "${yellow}\n==> ${green}${1} ${red}[y/n]${yellow}\n==> "
+    COUNT=$((${#1} + 6))
+    until [[ ${CONFIRM} =~ ^(y|n|Y|N|yes|no|Yes|No|YES|NO)$ ]]; do
+        echo -ne "${YELLOW}\n==> ${GREEN}${1} ${RED}[y/n]${YELLOW}\n==> "
         _end
-        read -r confirm
+        read -r CONFIRM
     done
 }
 
 # Ask some information
 _prompt() {
-    lenth=${@}
-    count=${#lenth}
-    echo -ne "\n${yellow}==> ${green}${1} ${red}${2}"
-    echo -ne "${yellow}\n==> "
+    LENTH=${@}
+    COUNT=${#lenth}
+    echo -ne "\n${YELLOW}==> ${GREEN}${1} ${RED}${2}"
+    echo -ne "${YELLOW}\n==> "
     _end
 }
 
 # Display the end of select, confirm and prompt functions
 _end() {
-    for char in $(seq ${count}); do
+    for char in $(seq ${COUNT}); do
         echo -ne "-"
     done
-    echo -ne "\n==> ${nc}"
+    echo -ne "\n==> ${NC}"
 }
 
 #                      ARCHBOOT_SYSTEM MANAGEMENT
@@ -198,25 +198,25 @@ fi
 
 # Download base sources
 _confirm "Start downloading sources from github?"
-case ${confirm} in
+case ${CONFIRM} in
     y|Y|yes|Yes|YES)
         _info "Downloading base sources"
-        _wget ${_url}/src/arch/base            # to install Base system
-        _wget ${_url}/src/arch/bootloader      # to install Grub2 bootloader
-        _wget ${_url}/src/arch/firmware        # to get user firmware
-        _wget ${_url}/src/arch/mirrorlist      # to get mirrorlist & timezone
-        _wget ${_url}/src/arch/mounting        # to mount partitions & swap
-        _wget ${_url}/src/arch/partition       # to create table & partitions
-        _wget ${_url}/src/arch/user            # to get user variables
-        _wget ${_url}/src/apps/system_apps     # to get system apps
-        _wget ${_url}/conf/language            # to get language code
-        _wget ${_url}/conf/timezone            # to get timezone
+        _wget ${URL}/src/arch/base            # to install Base system
+        _wget ${URL}/src/arch/bootloader      # to install Grub2 bootloader
+        _wget ${URL}/src/arch/firmware        # to get user firmware
+        _wget ${URL}/src/arch/mirrorlist      # to get mirrorlist & timezone
+        _wget ${URL}/src/arch/mounting        # to mount partitions & swap
+        _wget ${URL}/src/arch/partition       # to create table & partitions
+        _wget ${URL}/src/arch/user            # to get user variables
+        _wget ${URL}/src/apps/system_apps     # to get system apps
+        _wget ${URL}/conf/language            # to get language code
+        _wget ${URL}/conf/timezone            # to get timezone
         ;;
     *)
         exit
         ;;
 esac
-unset confirm
+unset CONFIRM
 
 # Import base sources
 _info "Importing base sources"
@@ -227,16 +227,16 @@ source ./mounting; source ./partition; source ./user; source ./system_apps
 _get_user_variables
 
 # Desktop Environment
-if [[ ! -z ${desktop+x} ]]; then
+if [[ ! -z ${DESKTOP+x} ]]; then
 
     # Download desktop sources
     _info "Downloading desktop sources"
-    _wget ${_url}/src/arch/vga             # to scan/install VGA Controller
-    _wget ${_url}/src/arch/desktop         # to install Desktop Environment
-    _wget ${_url}/src/arch/display         # to install Display Manager
-    _wget ${_url}/src/apps/vga_apps        # to get VGA apps
-    _wget ${_url}/src/apps/desktop_apps    # to get Desktop apps
-    _wget ${_url}/src/apps/display_apps    # to get Display Manager apps
+    _wget ${URL}/src/arch/vga             # to scan/install VGA Controller
+    _wget ${URL}/src/arch/desktop         # to install Desktop Environment
+    _wget ${URL}/src/arch/display         # to install Display Manager
+    _wget ${URL}/src/apps/vga_apps        # to get VGA apps
+    _wget ${URL}/src/apps/desktop_apps    # to get Desktop apps
+    _wget ${URL}/src/apps/display_apps    # to get Display Manager apps
 
     # Import desktop sources
     _info "Importing desktop sources"
@@ -244,16 +244,14 @@ if [[ ! -z ${desktop+x} ]]; then
     source ./vga_apps; source ./desktop_apps; source ./display_apps
 
     # VGA Driver or kernel mode setting?
-    _note "enter NO to activate kernel mode setting"
+    _note "enter NO to use kernel mode setting"
     _confirm "Do you wish to install VGA Driver?"
-    case ${confirm} in
+    case ${CONFIRM} in
         y|Y|yes|Yes|YES)
-            # Get VGA Controller
             _get_vga_controller
-            modsetting="true"
             ;;
     esac
-    unset confirm
+    unset CONFIRM
 fi
 
 #                       ARCHBOOT_SYSTEM PREPARE
@@ -269,7 +267,7 @@ _firmware; _mirrorlist; _timezone; _clock; _logs
 # Partitioning
 _note "enter NO to activate custom partitioning"
 _confirm "Do you wish to install Arch Linux on a dedicated disk?"
-case ${confirm} in
+case ${CONFIRM} in
     y|Y|yes|Yes|YES)
         _default_partitioning_scheme
         ;;
@@ -277,7 +275,7 @@ case ${confirm} in
         _custom_partitioning_scheme
         ;;
 esac
-unset confirm
+unset CONFIRM
 
 # Mount
 _mount_partitions
@@ -295,32 +293,32 @@ _note "system is ready to rumble! Partitions mounted & swap activated!"
 # ============================================================================
 
 _confirm "Do you wish to install Arch Linux now?"
-case ${confirm} in
+case ${CONFIRM} in
     y|Y|yes|Yes|YES)
 
         # Install Arch Linux base system
-        (_install_base; _install_bootloader) 2>&1 | tee -a ${log}
+        (_install_base; _install_bootloader) 2>&1 | tee -a ${LOG}
 
         # Install VGA Driver
-        if [[ ! -z ${modsetting+x} ]]; then
-            (_install_vga_driver) 2>&1 | tee -a ${log}
+        if [[ ! -z ${VGA_DRIVER+x} ]]; then
+            (_install_vga_driver) 2>&1 | tee -a ${LOG}
         fi
 
         # Install desktop environment & display manager
-        if [[ ! -z ${desktop+x} ]]; then
+        if [[ ! -z ${DESKTOP+x} ]]; then
             (_install_desktop_environment; _install_display_manager; \
-            _configure_desktop_environment) 2>&1 | tee -a ${log}
+            _configure_desktop_environment) 2>&1 | tee -a ${LOG}
         fi
 
         # User rights
-        if [[ ! -z ${power+x} ]]; then
-            (_grant_user_power) 2>&1 | tee -a ${log}
+        if [[ ! -z ${POWER+x} ]]; then
+            (_grant_user_power) 2>&1 | tee -a ${LOG}
         fi
 
         # Logfile path
         _info "Setting logfile path"
-        mkdir /mnt/var/log/${__appname__}
-        cp ${log} /mnt/var/log/${__appname__}/
+        mkdir /mnt/var/log/${APPNAME}
+        cp ${LOG} /mnt/var/log/${APPNAME}/
 
         # Success notes
         _note "Arch Linux installation successful!"
@@ -331,7 +329,7 @@ case ${confirm} in
         _error "aborted by user!"
         ;;
 esac
-unset confirm
+unset CONFIRM
 
 #                       ARCHBOOT_SYSTEM REBOOT
 # ============================================================================
@@ -340,9 +338,9 @@ unset confirm
 # Telegram chat: t.me/archboot - Have fun, take care and give a star!
 # ============================================================================
 
-_note "${__appname__} ${__version__} by ${__author__} under ${__license__}"
+_note "${APPNAME} ${VERSION} by ${AUTHOR} under ${LICENSE}"
 _confirm "Do you want to reboot your computer now?"
-case ${confirm} in
+case ${CONFIRM} in
     y|Y|yes|Yes|YES)
         umount -R /mnt
         _reboot
