error management

diff --git a/archboot b/archboot
--- a/archboot
+++ b/archboot
@@ -71,22 +71,24 @@ _clock() {
     hwclock --systohc
 }
 
-# Function to display errors
-_error() {
-    echo -e "${red}\n\nError: ${yellow}${1}${nc}\n" >&2
-    for d in $(seq 10 -1 1)
-    do
-        echo -ne "\r\033[K${green}System will reboot in ${d}s...${nc}"
-        sleep 1
-    done
-    echo
-    reboot
+# Function to check error
+_check() {
+    "$@"
+    local status=$?
+    if [ ${status} -ne 0 ]; then
+        echo -e "${red}\n\nError: ${yellow}${1}. Please try again.${nc}\n" >&2
+        for d in $(seq 10 -1 1); do
+            echo -ne "\r\033[K${green}System will reboot in ${d}s...${nc}\n"
+            sleep 1
+        done
+        reboot
+    fi
+    return ${status}
 }
 
 # Function to ask confirmation (Yes/No)
 _confirm() {
-    until [[ ${confirm} =~ ^[yn]$ ]]
-    do
+    until [[ ${confirm} =~ ^[yn]$ ]]; do
         echo -e "${yellow}\n==> ${green}${1} ${red}[y/n]${yellow}" >&2
         echo -e "==> \
 -------------------------------------------------------" >&2
@@ -101,8 +103,7 @@ _prompt() {
     echo -e "==> ${green}${1} ${red}${2} ${green}${3} ${red}${4} \
 ${green}${5} ${red}${6} ${green}${7} ${red}${8} ${green}${9} \
 ${red}${10} ${green}${11} ${red}${12}${yellow}" >&2
-    if [[ ! -z ${13+x} ]]
-    then
+    if [[ ! -z ${13+x} ]]; then
         echo -e "==> ${green}${13} ${red}${14} ${green}${15} ${red}${16} \
 ${green}${17} ${red}${18} ${green}${19} ${red}${20}${yellow}" >&2
     fi
@@ -131,8 +132,7 @@ _banner
 # Check Internet Connection
 _info "Check Internet Connection"
 ping -c 1 archlinux.org >/dev/null 2>&1
-if [[ $? == 0 ]]
-then
+if [[ $? == 0 ]]; then
     _note "OK, you are connected to Internet."
 else
     _error "you are not connected to Internet. \
@@ -141,8 +141,7 @@ fi
 
 # Download base sources
 _confirm "Start downloading sources from github?"
-if [[ ${confirm} == "y" ]]
-then
+if [[ ${confirm} == "y" ]]; then
     _info "Downloading sources"
     _wget ${_url}/src/arch/base            # to install ArchLinux Base system
     _wget ${_url}/src/arch/bootloader      # to install Grub2 bootloader
@@ -154,7 +153,8 @@ then
     _wget ${_url}/conf/language            # to get language code
     _wget ${_url}/conf/timezone            # to get region code
 else
-    echo; exit
+    echo
+    exit
 fi
 unset confirm
 
@@ -164,65 +164,51 @@ source ./base; source ./bootloader; source ./firmware
 source ./mounting; source ./partition; source ./user; source ./system_apps
 
 # Prepare the system
-_user_infos; _clock; _logs; _firmware; _partition
+_user_infos; _clock; _logs; _firmware; _partition; mounting
 
-# Mount partitions & check for errors
-_mounting
-if [[ $? -eq 0 ]]
-then
-    _note "system ready! Partitions mounted & swap activated."
+_note "system ready! Partitions mounted & swap activated."
 
-    #
-    # Start the installation
-    #
+# Install ArchLinux
+_confirm "Do you wish to install ArchLinux now?"
+if [[ ${confirm} == "y" ]]; then
+    (_base; _bootloader) 2>&1 | tee -a "${log}"
+else
+    _error "aborted by user! Please try again."
+fi
+unset confirm
 
-    # Install ArchLinux
-    _confirm "Do you wish to install ArchLinux now?"
-    if [[ ${confirm} == "y" ]]
-    then
-        (_base; _bootloader) 2>&1 | tee -a "${log}"
-    else
-        _error "aborted by user! Please try again."
-    fi
-    unset confirm
+# Install Desktop Environment
+if [[ ! -z ${desktop+x} ]]; then
 
-    # Install Desktop Environment
-    if [[ ! -z ${desktop+x} ]]
-    then
+    # Download desktop sources
+    _info "Downloading desktop sources"
+    _wget ${_url}/src/arch/desktop         # to install Desktop Environment
+    _wget ${_url}/src/arch/display         # to configure Display Manager
+    _wget ${_url}/src/apps/desktop_apps    # to load desktop apps
 
-        # Download desktop sources
-        _info "Downloading desktop sources"
-        _wget ${_url}/src/arch/desktop         # to install Desktop Environment
-        _wget ${_url}/src/arch/display         # to configure Display Manager
-        _wget ${_url}/src/apps/desktop_apps    # to load desktop apps
+    # Import desktop sources
+    _info "Importing sources"
+    source ./desktop; source ./display; source ./desktop_apps
 
-        # Import desktop sources
-        _info "Importing sources"
-        source ./desktop; source ./display; source ./desktop_apps
+    # Install desktop environment
+    (_install_DE; _display_manager; _DE_settings) 2>&1 | tee -a "${log}"
+fi
 
-        # Install desktop environment
-        (_install_DE; _display_manager; _DE_settings) 2>&1 | tee -a "${log}"
-    fi
+# Logfile path
+_info "Setting logfile path"
+mkdir /mnt/var/log/archboot
+cp "${logfile}" /mnt/var/log/archboot/
 
-    # Logfile path
-    _info "Setting logfile path"
-    mkdir /mnt/var/log/archboot
-    cp "${logfile}" /mnt/var/log/archboot/
-
-    # Success notes
-    _note "Installation successful! \
+# Success notes
+_note "Installation successful! \
 ${__appname__} ${__version__} by ${__author__} under ${__license__}"
 
-    # Reboot
-    _confirm "Do you want to reboot your computer now?"
-    if [[ ${confirm} == "y" ]]
-    then
-        umount -R /mnt; reboot
-    else
-        echo
-        exit
-    fi
-
+# Reboot
+_confirm "Do you want to reboot your computer now?"
+if [[ ${confirm} == "y" ]]; then
+    umount -R /mnt
+    reboot
 else
-    _error "bad partitionning! Error occur during mount. Please try again."
+    echo
+    exit
 fi
