Prevent running archboot from repository folder

diff --git a/archboot b/archboot
--- a/archboot
+++ b/archboot
@@ -36,14 +36,19 @@ ${NC}
 # select an option, ask some information to the user or to get install logs.
 # ============================================================================
 
-### Github url for sources and images
+### Github urls (current branch and gh-pages)
 URL="https://raw.githubusercontent.com/${AUTHOR}/${APPNAME}/${BRANCH}"
 export GHPAGES=\
 "https://raw.githubusercontent.com/${AUTHOR}/${APPNAME}/gh-pages"
 
 ### Shell colors
 RED="\e[1;31m"; GREEN="\e[1;32m"; YELLOW="\e[1;33m"
-BLUE="\e[1;34m"; CYAN="\e[1;36m"; NC="\e[0m"
+BLUE="\e[1;34m"; CYAN="\e[1;36m"; BOLD="\e[1;37m"; NC="\e[0m"
+
+### Display some notes
+_note() {
+    echo -e "${RED}\nNote: ${BLUE}${1}${NC}"
+}
 
 ### Display install steps
 _info() {
@@ -51,103 +56,11 @@ _info() {
     sleep 1
 }
 
-### Display some notes
-_note() {
-    echo -e "${RED}\nNote: ${BLUE}${1}${NC}"
-}
-
-### Delete sources and umount partitions
-_cleanup() {
-    echo -e "\nCleaning up ${APPNAME}..."
-    SRC=(base bootloader desktop display firmware gpu_driver mirrorlist \
-mounting partitioning user desktop_apps display_apps gpu_apps system_apps \
-00-keyboard.conf language loader.conf timezone xinitrc xprofile \
-background.png Grub2-themes archboot* *_vars.log)
-    for SOURCE in "${SRC[@]}"; do
-        if [[ -f "${SOURCE}" ]]; then
-            rm -rfv "${SOURCE}"
-        fi
-    done
-    if mount | grep /mnt; then
-        umount -Rfv /mnt
-    fi
-    echo && echo -e \
-"${RED}${APPNAME} ${VERSION} by ${AUTHOR} under ${LICENSE}${NC}"
-}
-
-### Display error and cleanup
-_error() {
-    echo -e "\n${RED}Error: ${YELLOW}${*}${NC}"
-    sleep 1; _cleanup
-    _note "you must reboot to prevent unreconized system changes.\n"
-    kill -9 $$
-}
-
-### Cleanup on keyboard interrupt
-trap '_error "keyboard interrupt!"' 1 2 3 6
-
-### Reboot with 10s timeout
-_reboot() {
-    for ((SECOND=10; SECOND>=1; SECOND--)); do
-        echo -ne "\r\033[K${GREEN}System will reboot in ${SECOND}s...${NC}"
-        sleep 1
-    done
-    reboot; exit 0
-}
-
-### Check and return command status
-_check() {
-    "${@}"
-    local STATUS=$?
-    if [[ ${STATUS} -ne 0 ]]; then
-        _error "${@}"
-    fi
-    return "${STATUS}"
-}
-
-### Set system clock
-_clock() {
-    _info "Setting system clock"
-    _check timedatectl set-timezone "${TIMEZONE}"
-    _check timedatectl set-ntp true
-    _check ntpd -qg
-    _check hwclock --systohc
-    timedatectl show
-}
-
-### Set logfiles
-_logs() {
-    _info "Setting ${APPNAME} logs"
-    DATETIME=$(_check date '+%d-%m-%Y_%Hh%M')
-    INSTALL_LOG="${APPNAME}-${VERSION}_${DATETIME}.log"
-    INPUTS_LOG="${USER_NAME}_${DATETIME}.log"
-    _archboot_banner > "${INSTALL_LOG}"
-    _archboot_banner > "${INPUTS_LOG}"
-    echo "done"
-}
-
-### Download show progress bar only
-_wget() {
-    wget "${1}" -q --show-progress
-}
-
-### Execute action in chrooted environment
-_chroot() {
-    arch-chroot /mnt /bin/bash <<EOF
-    ${1}
-EOF
-}
-
-### Select an option
-_select() {
-    COUNT=0
-    echo -ne "${YELLOW}\n==> "
-    for ENTRY in "${@}"; do
-        echo -ne "${RED}[$((++COUNT))] ${GREEN}${ENTRY} ${NC}"
-    done
+### Ask some information
+_prompt() {
     LENTH=${*}
-    NUMBER=$((${#*} * 4))
-    COUNT=$((${#LENTH} + NUMBER + 1))
+    COUNT=${#LENTH}
+    echo -ne "\n${YELLOW}==> ${GREEN}${1} ${RED}${2}"
     echo -ne "${YELLOW}\n==> "
     for ((CHAR=1; CHAR<=COUNT; CHAR++)); do echo -ne "-"; done
     echo -ne "\n==> ${NC}"
@@ -165,14 +78,106 @@ _confirm() {
     done
 }
 
-### Ask some information
-_prompt() {
+### Select an option
+_select() {
+    COUNT=0
+    echo -ne "${YELLOW}\n==> "
+    for ENTRY in "${@}"; do
+        echo -ne "${RED}[$((++COUNT))] ${GREEN}${ENTRY} ${NC}"
+    done
     LENTH=${*}
-    COUNT=${#LENTH}
-    echo -ne "\n${YELLOW}==> ${GREEN}${1} ${RED}${2}"
+    NUMBER=$((${#*} * 4))
+    COUNT=$((${#LENTH} + NUMBER + 1))
     echo -ne "${YELLOW}\n==> "
     for ((CHAR=1; CHAR<=COUNT; CHAR++)); do echo -ne "-"; done
     echo -ne "\n==> ${NC}"
+}
+
+### Download show progress bar only
+_wget() {
+    wget "${1}" -q --show-progress
+}
+
+### Execute action in chrooted environment
+_chroot() {
+    arch-chroot /mnt /bin/bash <<EOF
+    ${1}
+EOF
+}
+
+### Check and return command status
+_check() {
+    "${@}"
+    local STATUS=$?
+    if [[ ${STATUS} -ne 0 ]]; then
+        _error "${@}"
+    fi
+    return "${STATUS}"
+}
+
+### Display error, cleanup and kill
+_error() {
+    echo -e "\n${RED}Error: ${YELLOW}${*}${NC}"
+    sleep 1; _cleanup
+    _note "you must reboot to prevent unreconized system changes.\n"
+    _exit_msg
+    kill -9 $$
+}
+
+### Cleanup on keyboard interrupt
+trap '_error "keyboard interrupt!"' 1 2 3 6
+
+### Delete sources and umount partitions
+_cleanup() {
+    echo -e "\nCleaning up ${APPNAME}..."
+    SRC=(base bootloader desktop display firmware gpu_driver mirrorlist \
+mounting partitioning user desktop_apps display_apps gpu_apps system_apps \
+00-keyboard.conf language loader.conf timezone xinitrc xprofile \
+background.png Grub2-themes archboot* *_vars.log)
+    for SOURCE in "${SRC[@]}"; do
+        if [[ -f "${SOURCE}" ]]; then
+            rm -rfv "${SOURCE}"
+        fi
+    done
+    if mount | grep /mnt; then
+        umount -Rfv /mnt
+    fi
+}
+
+### Reboot with 10s timeout
+_reboot() {
+    for ((SECOND=10; SECOND>=1; SECOND--)); do
+        echo -ne "\r\033[K${GREEN}System will reboot in ${SECOND}s...${NC}"
+        sleep 1
+    done
+    reboot; exit 0
+}
+
+### Set logfiles
+_logs() {
+    _info "Setting ${APPNAME} logs"
+    DATETIME=$(_check date '+%d-%m-%Y_%Hh%M')
+    INSTALL_LOG="${APPNAME}-${VERSION}_${DATETIME}.log"
+    INPUTS_LOG="${USER_NAME}_${DATETIME}.log"
+    _archboot_banner > "${INSTALL_LOG}"
+    _archboot_banner > "${INPUTS_LOG}"
+    echo "done"
+}
+
+### Set system clock
+_clock() {
+    _info "Setting system clock"
+    _check timedatectl set-timezone "${TIMEZONE}"
+    _check timedatectl set-ntp true
+    _check ntpd -qg
+    _check hwclock --systohc
+    timedatectl show
+}
+
+### Say goodbye
+_exit_msg() {
+    echo -e "\n${BLUE}${APPNAME}-${VERSION}${NC}${BOLD} \
+by ${AUTHOR}${NC} ${RED}under ${LICENSE}${NC}"
 }
 
 #             START SCRIPT - IMPORT SOURCES - GET USER VARIABLES
@@ -187,6 +192,15 @@ _prompt() {
 
 ### Display archboot banner
 _archboot_banner
+
+### Prevent running archboot from repository folder
+CHECK_GITHUB=(LICENSE README.md STATS.md src apps conf .github .git)
+for FILE in "${CHECK_GITHUB[@]}"; do
+    if [[ -f ${FILE} ]]; then
+        _note "please do not run ${APPNAME} from github repository folder!"
+        _exit_msg; sleep 1; kill -9 $$
+    fi
+done
 
 ### Check Internet Connection
 _info "Checking Internet connection"
@@ -214,7 +228,7 @@ case ${CONFIRM} in
         _wget "${URL}/conf/timezone"           # to get timezone code
         ;;
     *)
-        _cleanup; exit 0
+        _cleanup; _exit_msg; exit 0
         ;;
 esac
 
@@ -254,10 +268,8 @@ if [[ ${DESKTOP} ]]; then
     # GPU Driver or kernel mode setting?
     _note "enter NO to use kernel mode setting."
     _confirm "Do you wish to install GPU Driver?"
-    case ${CONFIRM} in
-        y|Y|yes|Yes|YES)
-            _get_gpu_driver
-            ;;
+    case ${CONFIRM} in y|Y|yes|Yes|YES)
+        _get_gpu_driver;;
     esac
 fi
 
@@ -361,12 +373,10 @@ esac
 _confirm "Do you wish to reboot your computer now?"
 case ${CONFIRM} in
     y|Y|yes|Yes|YES)
-        _cleanup
-        _reboot
+        _cleanup; _exit_msg; _reboot
         ;;
     *)
-        _cleanup
-        exit 0
+        _cleanup; _exit_msg; exit 0
         ;;
 esac
 
