update description

diff --git a/archboot b/archboot
--- a/archboot
+++ b/archboot
@@ -2,7 +2,7 @@
 __appname__="archboot"
 __version__="v2.7.4"
 __branch__="master"
-__author__="@grm34"
+__author__="grm34"
 __license__="Apache v2.0 License"
 
 _banner() {
@@ -11,12 +11,17 @@ _banner() {
     echo -e "   / \   _ __  __| |__ | |__   ___   ___ | |_ " >&2
     echo -e "  / _ \ | '__/ __| '_ \| '_ \ / _ \ / _ \| __|" >&2
     echo -e " / ___ \| | | (__| | | | |_) | (_) | (_) | |_ " >&2
-    echo -e "/_/   \_\_|  \___|_| |_|_.__/ \___/ \___/ \__|_${green}${__version__}${nc}\n" >&2
-    echo -e "Welcome in archboot, a script made with love by grm34!" >&2
-    echo -e "This script perform an automatic install of Arch Linux" >&2
-    echo -e "Pretty simple, it only ask you for hostname, username," >&2
-    echo -e "password, which disk to use, required partitions size," >&2
-    echo -e "language & if you wish to install desktop environment." >&2
+    echo -e "/_/   \_\_|  \___|_| |_|_.__/ \___/ \___/ \__|_${green}${__version__}\n" >&2
+    echo -e "${blue}Welcome in archboot, a script made with love by ${__author__}${nc}\n" >&2
+    echo -e "Arch Linux is a light and fast distribution whose concept" >&2
+    echo -e "is to remain as simple as possible. In the same purpose this" >&2
+    echo -e "script performs minimalist installation. It only installs the" >&2
+    echo -e "required packages, in order to give free choice to the user." >&2
+    echo -e "Pretty simple, it just prompt for hostname,username, password," >&2
+    echo -e "which disk to use, required partitions, language, timezone and" >&2
+    echo -e "if you wish to install a desktop environment. According to the" >&2
+    echo -e "chosen one and in order to get complete support, additionals" >&2
+    echo -e "packages may be required." >&2
 }
 
 #
