Update help/usage scheme

diff --git a/archboot b/archboot
--- a/archboot
+++ b/archboot
@@ -39,7 +39,7 @@ ${NC}
 ARCHBOOT_LANGUAGE="ENGLISH"
 
 ### Shell colors
-RED="\e[1;31m"; GREEN="\e[1;32m"; YELLOW="\e[1;33m"
+RED="\e[1;31m"; GREEN="\e[1;32m"; YELLOW="\e[1;33m"; GR="\e[3;93m"
 BLUE="\e[1;34m"; CYAN="\e[1;36m"; BOLD="\e[1;37m"; NC="\e[0m"
 
 ### Usage
@@ -57,16 +57,34 @@ ${BOLD}Usage: ${NC}sh $(basename "$0") [options]
                         french
                         german (by @At1768)
 
-For more information, see the wiki: <https://github.com/grm34/archboot/wiki>"
+For more information, see the wiki: ${GR}<http://tiny.cc/archboot-wiki>${NC}"
 
-# Transform long options to short ones
+### Prevent too much arguments
+if [[ ${#} -gt 2 ]]; then
+    echo -e "${USAGE}\n"
+    echo -e "${RED}Error:${NC} too much arguments ${*}"
+    rm -f old_vars.log;  exit 1
+fi
+
+### Match illegal options
+read -ra ARGS <<< "${@}"
+
+if [[ ${#} == 0 || ${ARGS[0]} =~ ^--?[a-z]{1,4}$ ]]; then
+    sleep 0
+else
+    echo -e "${USAGE}\n"
+    echo -e "${RED}Error:${NC} illegal option ${*}"
+    rm -f old_vars.log;  exit 1
+fi
+
+### Transform long options to short ones
 for OPTION in "${@}"; do
     shift
 
     case ${OPTION} in
         "--help"|"?") set -- "${@}" "-h";;
         "--lang") set -- "${@}" "-l${*}";;
-        *)        set -- "$@" "${OPTION}"
+        *) set -- "${@}" "${OPTION}"
     esac
 done
 
@@ -78,7 +96,7 @@ while getopts ':hl:' OPTION; do
         :) echo -e "${USAGE}\n"
             echo -e "${RED}Error:${NC} missing argument for -${OPTARG}"
             rm -f old_vars.log; exit 1;;
-        \?) echo -e "${USAGE}\n"
+        *) echo -e "${USAGE}\n"
             echo -e "${RED}Error:${NC} invalid option -${OPTARG}"
             rm -f old_vars.log; exit 1
    esac
@@ -86,16 +104,6 @@ done
 
 ### Remove options from positional parameters
 shift $((OPTIND - 1))
-
-## Prevent running script without args
-if [[ $# != 0 ]]; then
-    case ${@} in
-        "--lang"|"-l"|"--help"|"-h"|"?") ;;
-        *) echo -e "${USAGE}\n"
-            echo -e "${RED}Error:${NC} illegal option ${*}"
-            rm -f old_vars.log;  exit 1
-    esac
-fi
 
 ### Github urls (current branch and gh-pages branch)
 export URL="https://raw.githubusercontent.com/${AUTHOR}/${APPNAME}/${BRANCH}"
