Better way to handle help/usage

diff --git a/archboot b/archboot
--- a/archboot
+++ b/archboot
@@ -29,91 +29,29 @@ ${NC}
 #                      SHARED VARIABLES & FUNCTIONS
 # ============================================================================
 # Here we define all required variables and functions to manage archboot.
-# Variables are pretty simple such as define usage, urls and shell colors.
-# Functions are used to handle help, install steps, notes, errors or to do
-# some actions like cleanup after fatal error, execute cmd in chrooted env,
+# Variables are pretty simple such as define repository url and shell colors.
+# Functions are used to handle install steps, notes, errors or to do some
+# actions like cleanup after fatal error, execute cmd in chrooted env,
 # select an option, ask some information to the user or get install logs.
 # ============================================================================
 
 ### Default language
-ARCHBOOT_LANGUAGE="ENGLISH"
+ARCHBOOT_LANGUAGE="english"
+
+### Default error msg (required when locale not sourced)
+MSG_ERROR="you must reboot to prevent unreconized system changes."
+MSG_ERROR_GIT="do not run archboot from git repository folder!"
+MSG_KEYBOARD="keyboard interrupt!"
+MSG_CLEANUP="Cleaning up sources"
 
 ### Shell colors
-RED="\e[1;31m"; GREEN="\e[1;32m"; YELLOW="\e[1;33m"; GR="\e[3;93m"
+RED="\e[1;31m"; GREEN="\e[1;32m"; YELLOW="\e[1;33m"; GREY="\e[3;93m"
 BLUE="\e[1;34m"; CYAN="\e[1;36m"; BOLD="\e[1;37m"; NC="\e[0m"
-
-### Usage
-USAGE=\
-${BLUE}"Arch Linux Installer - A script made with love by ${AUTHOR}${NC}
-
-${BOLD}Usage: ${NC}sh $(basename "$0") [options]
-
-    ${BOLD}Options${NC}
-        -h, --help      show this help message
-        -l, --lang      set language
-
-    ${BOLD}Languages${NC}
-        -l, --lang      english
-                        french
-                        german (by @At1768)
-
-For more information, see the wiki: ${GR}<http://tiny.cc/archboot-wiki>${NC}"
-
-### Prevent too much arguments
-if [[ ${#} -gt 2 ]]; then
-    echo -e "${USAGE}\n"
-    echo -e "${RED}Error:${NC} too much arguments ${*}"
-    rm -f old_vars.log;  exit 1
-fi
-
-### Match illegal options
-read -ra ARGS <<< "${@}"
-
-if [[ ${#} == 0 || ${ARGS[0]} =~ ^--?[a-z]{1,4}$ ]]; then
-    sleep 0
-else
-    echo -e "${USAGE}\n"
-    echo -e "${RED}Error:${NC} illegal option ${*}"
-    rm -f old_vars.log;  exit 1
-fi
-
-### Transform long options to short ones
-for OPTION in "${@}"; do
-    shift
-
-    case ${OPTION} in
-        "--help"|"?") set -- "${@}" "-h";;
-        "--lang") set -- "${@}" "-l${*}";;
-        *) set -- "${@}" "${OPTION}"
-    esac
-done
-
-### Option processing
-while getopts ':hl:' OPTION; do
-    case ${OPTION} in
-        h) echo -e "${USAGE}"; exit;;
-        l) ARCHBOOT_LANGUAGE=${OPTARG};;
-        :) echo -e "${USAGE}\n"
-            echo -e "${RED}Error:${NC} missing argument for -${OPTARG}"
-            rm -f old_vars.log; exit 1;;
-        *) echo -e "${USAGE}\n"
-            echo -e "${RED}Error:${NC} invalid option -${OPTARG}"
-            rm -f old_vars.log; exit 1
-   esac
-done
-
-### Remove options from positional parameters
-shift $((OPTIND - 1))
 
 ### Github urls (current branch and gh-pages branch)
 export URL="https://raw.githubusercontent.com/${AUTHOR}/${APPNAME}/${BRANCH}"
 export GHPAGES=\
 "https://raw.githubusercontent.com/${AUTHOR}/${APPNAME}/gh-pages"
-
-### Default error msg (required when locale not sourced)
-MSG_ERROR="you must reboot to prevent unreconized system changes."
-MSG_KEYBOARD="keyboard interrupt!"
-MSG_CLEANUP="Cleaning up sources"
 
 ### Display some notes
 _note() {
@@ -241,6 +179,86 @@ _exit_msg() {
 ${AUTHOR} ${RED}under ${LICENSE} ${GREEN}>>>${NC}"""
 }
 
+#                         MANAGE HELP AND USAGE
+# ============================================================================
+# Here we manage help and usage to properly describe archboot. Options are
+# pretty simple, only to show help message/usage and to select language.
+# We first prevent user argument errors by simply matching options before
+# running process. Usage: sh archboot [options] (e.g., sh archboot -l french)
+# ============================================================================
+
+### Usage
+USAGE=\
+${BLUE}"Arch Linux Installer - A script made with love by ${AUTHOR}${NC}
+
+${BOLD}Usage: ${NC}sh $(basename "$0") [options]
+
+    ${BOLD}Options${NC}
+        -h, --help      show this help message
+        -l, --lang      set language
+
+    ${BOLD}Languages${NC}
+        -l, --lang      english
+                        french
+                        german (by @At1768)
+
+${BOLD}For more information, see the wiki: \
+${GREY}<http://tiny.cc/archboot-wiki>${NC}"
+
+### Prevent too much arguments
+if [[ ${#} -gt 2 ]]; then
+    echo -e "${RED}Error:${NC} too much arguments ${*}\n"
+    echo -e "${USAGE}"
+    rm -f old_vars.log; _exit_msg; exit 1
+fi
+
+### Match legal option or exit
+read -ra ARGS <<< "${@}"
+
+if [[ ${#} == 0 || ${ARGS[0]} =~ ^(-l$|--lang$|-h$|--help$) ]]; then
+    true
+else
+    echo -e "${RED}Error:${NC} invalid option ${*}\n"
+    echo -e "${USAGE}"
+    rm -f old_vars.log; _exit_msg; exit 1
+fi
+
+### Transform long options to short ones
+for OPTION in "${@}"; do
+    shift
+
+    case ${OPTION} in
+        "--help") set -- "${@}" "-h";;
+        "--lang") set -- "${@}" "-l${*}";;
+        *) set -- "${@}" "${OPTION}"
+    esac
+done
+
+### Option processing
+while getopts ':hl:' OPTION; do
+    case ${OPTION} in
+        h) echo -e "${USAGE}"; rm -f old_vars.log; _exit_msg; exit 0;;
+        l) ARCHBOOT_LANGUAGE=${OPTARG};;
+        :) echo -e "${RED}Error:${NC} missing argument for -${OPTARG}\n"
+            echo -e "${USAGE}"
+            rm -f old_vars.log; _exit_msg; exit 1;;
+        *) true
+   esac
+done
+
+### Remove options from positional parameters
+shift $((OPTIND - 1))
+
+### Prevent running script from repository folder
+CHECK_GITHUB=(LICENSE README.md STATS.md conf locale src .github .git)
+
+for FILE in "${CHECK_GITHUB[@]}"; do
+    if [[ -f ${FILE} || -d ${FILE} ]]; then
+        echo -e "${RED}Error: ${YELLOW}${MSG_ERROR_GIT}${NC}"
+        rm -f old_vars.log; _exit_msg; exit 1
+    fi
+done
+
 #             START SCRIPT - IMPORT SOURCES - GET USER VARIABLES
 # ============================================================================
 # Here we check internet connection before downloading and importing sources.
@@ -251,22 +269,12 @@ ${AUTHOR} ${RED}under ${LICENSE} ${GREEN}>>>${NC}"""
 # Kernel mode setting support: in this case no GPU Driver will be installed.
 # ============================================================================
 
-### Display archboot banner
-_archboot_banner
-
-### Prevent running from repository folder
-CHECK_GITHUB=(LICENSE README.md STATS.md conf locale src .github .git)
-
-for FILE in "${CHECK_GITHUB[@]}"; do
-    if [[ -f ${FILE} || -d ${FILE} ]]; then
-        echo -e "${RED}Error: ${YELLOW}${MSG_ERROR_GIT}${NC}"
-        rm -f old_vars.log; _exit_msg; exit 1
-    fi
-done
-
 ### Set language
 _check wget -q "${URL}/locale/${ARCHBOOT_LANGUAGE,,}"
 _check source "./${ARCHBOOT_LANGUAGE,,}"
+
+### Display archboot banner
+_archboot_banner
 
 ### Check Internet Connection
 _info "${MSG_INTERNET}"
