Adds script help/usage

diff --git a/archboot b/archboot
--- a/archboot
+++ b/archboot
@@ -35,14 +35,70 @@ ${NC}
 # select an option, ask some information to the user or to get install logs.
 # ============================================================================
 
+### Shell colors
+RED="\e[1;31m"; GREEN="\e[1;32m"; YELLOW="\e[1;33m"
+BLUE="\e[1;34m"; CYAN="\e[1;36m"; BOLD="\e[1;37m"; NC="\e[0m"
+
+### Usage
+USAGE=\
+${BLUE}"Arch Linux Installer - A script made with love by ${AUTHOR}${NC}
+
+${BOLD}Usage: ${NC}sh $(basename "$0") [options]
+
+    ${BOLD}Options${NC}
+        -h, --help      show this help message
+        -l, --lang      set language
+
+    ${BOLD}Languages${NC}
+        -l, --lang      english
+                        french
+                        spanish
+
+For more information, see the wiki: <https://github.com/grm34/archboot/wiki>"
+
+# Transform long options to short ones
+for OPTION in "${@}"; do
+    shift
+    case ${OPTION} in
+        "--help"|"?") set -- "${@}" "-h";;
+        "--lang") set -- "${@}" "-l${*}";;
+        *)        set -- "$@" "${OPTION}"
+    esac
+done
+
+### Option processing
+ARCHBOOT_LANGUAGE="ENGLISH"
+
+while getopts ':hl:' OPTION; do
+    case ${OPTION} in
+        h) echo -e "${USAGE}"; exit;;
+        l) ARCHBOOT_LANGUAGE=${OPTARG};;
+        :) echo -e "${USAGE}\n"
+            echo -e "${RED}Error:${NC} missing argument for -${OPTARG}"
+            rm -f old_vars.log;  exit 1;;
+        \?) echo -e "${USAGE}\n"
+            echo -e "${RED}Error:${NC} illegal option -${OPTARG}"
+            rm -f old_vars.log;  exit 1
+   esac
+done
+
+### remove options from positional parameters
+shift $((OPTIND - 1))
+
+## Prevent running without args
+if [[ $# != 0 ]]; then
+    case ${@} in
+        "--lang"|"-l"|"--help"|"-h"|"?") ;;
+        *) echo -e "${USAGE}\n"
+            echo -e "${RED}Error:${NC} illegal option ${*}"
+            rm -f old_vars.log;  exit 1
+    esac
+fi
+
 ### Github urls (current branch and gh-pages)
 export URL="https://raw.githubusercontent.com/${AUTHOR}/${APPNAME}/${BRANCH}"
 export GHPAGES=\
 "https://raw.githubusercontent.com/${AUTHOR}/${APPNAME}/gh-pages"
-
-### Shell colors
-RED="\e[1;31m"; GREEN="\e[1;32m"; YELLOW="\e[1;33m"
-BLUE="\e[1;34m"; CYAN="\e[1;36m"; BOLD="\e[1;37m"; NC="\e[0m"
 
 ### Default error msg (required when locale not already sourced)
 MSG_ERROR="you must reboot to prevent unreconized system changes."
@@ -187,19 +243,22 @@ ${AUTHOR} ${RED}under ${LICENSE} ${GREEN}>>>${NC}"""
 ### Display archboot banner
 _archboot_banner
 
-### Prevent running archboot from repository folder
+### Prevent running from repository folder
 CHECK_GITHUB=(LICENSE README.md STATS.md conf locale src .github .git)
 
 for FILE in "${CHECK_GITHUB[@]}"; do
     if [[ -f ${FILE} || -d ${FILE} ]]; then
-        echo -e \
-"${RED}Error: ${YELLOW}do not run ${APPNAME} from git repository folder!${NC}"
-        rm -rf old_vars.log; _exit_msg; sleep 1; kill -9 $$
+        echo -e "${RED}Error: ${YELLOW}${MSG_ERROR_GIT}${NC}"
+        rm -f old_vars.log; _exit_msg; exit 1
     fi
 done
 
+### Set language
+_check wget -q "${URL}/locale/${ARCHBOOT_LANGUAGE,,}"
+_check source "./${ARCHBOOT_LANGUAGE,,}"
+
 ### Check Internet Connection
-_info "Checking Internet connection"
+_info "${MSG_INTERNET}"
 INTERNET=$(ping -c 1 archlinux.org)
 
 if [[ ${INTERNET} ]]; then
@@ -207,16 +266,6 @@ if [[ ${INTERNET} ]]; then
 else
     _error "you are not connected to Internet!"
 fi
-
-### archboot language
-until [[ ${USER_LANGUAGE} =~ ^[1-3]$ ]]; do
-    _select "ENGLISH" "FRENCH" "SPANISH (pending)"
-    read -r USER_LANGUAGE
-done
-LANGUAGE_CHOICE=(NONE ENGLISH FRENCH SPANISH)
-ARCHBOOT_LANGUAGE=${LANGUAGE_CHOICE[${USER_LANGUAGE}]}
-wget -q "${URL}/locale/${ARCHBOOT_LANGUAGE,,}"
-_check source "./${ARCHBOOT_LANGUAGE,,}"
 
 ### Download base sources
 _confirm "${MSG_CONFIRM_DL_SOURCES}"
@@ -235,9 +284,7 @@ case ${CONFIRM} in
         _wget "${URL}/conf/language"           # to get language code
         _wget "${URL}/conf/timezone"           # to get timezone code
         ;;
-    *)
-        _cleanup; _exit_msg; exit 0
-        ;;
+    *) _cleanup; _exit_msg; exit 0
 esac
 
 ### Import base sources
@@ -281,7 +328,7 @@ if [[ ${DESKTOP} ]]; then
     _confirm "${MSG_CONFIRM_GPU}"
 
     case ${CONFIRM} in
-        y|Y|yes|Yes|YES) _get_gpu_driver;;
+        y|Y|yes|Yes|YES) _get_gpu_driver
     esac
 fi
 
@@ -303,7 +350,7 @@ _confirm "${MSG_CONFIRM_DRIVE}"
 
 case ${CONFIRM} in
     y|Y|yes|Yes|YES) _default_partitioning_scheme;;
-    *) _custom_partitioning_scheme;;
+    *) _custom_partitioning_scheme
 esac
 
 ### Mount
@@ -381,7 +428,6 @@ RED=\|GREEN=\|YELLOW=\|BLUE=\|CYAN=\|NC=" > new_vars.log
     *)
         ### Install aborted
         _error "${MSG_ARCH_ABORTED}"
-        ;;
 esac
 
 #               CLEANUP SOURCES - UMOUNT PARTITIONS - REBOOT
@@ -395,7 +441,7 @@ _confirm "${MSG_CONFIRM_REBOOT}"
 
 case ${CONFIRM} in
     y|Y|yes|Yes|YES) _cleanup; _exit_msg; _reboot;;
-    *) _cleanup; _exit_msg; exit 0;;
+    *) _cleanup; _exit_msg; exit 0
 esac
 
 # archboot by grm34 under Apache License 2.0
