v2.5
Add description

diff --git a/archboot b/archboot
--- a/archboot
+++ b/archboot
@@ -17,6 +17,12 @@ _banner() {
     echo -e "   / _ \ | '__/ __| '_ \| '_ \ / _ \ / _ \| __|" >&2
     echo -e "  / ___ \| | | (__| | | | |_) | (_) | (_) | |_ " >&2
     echo -e " /_/   \_\_|  \___|_| |_|_.__/ \___/ \___/ \__| $__version__$nc" >&2
+    echo -e "\nWelcome in archboot, a script made with love by grm34!" >&2
+    echo -e "This script perform an automatic install of Archlinux." >&2
+    echo -e "Pretty simple, it only ask you for hostname, username," >&2
+    echo -e "password, which disk to use, required partitions sizes" >&2
+    echo -e "and if you wish or not to install desktop environment." >&2
+    echo -e "KDE | Gnome | Xfce4 | Lxde are available." >&2
 }
 
 # General functions
