v2.6.2
Clean bash ident

diff --git a/archboot b/archboot
--- a/archboot
+++ b/archboot
@@ -11,8 +11,8 @@ _banner() {
     echo -e "   / \   _ __  __| |__ | |__   ___   ___ | |_ " >&2
     echo -e "  / _ \ | '__/ __| '_ \| '_ \ / _ \ / _ \| __|" >&2
     echo -e " / ___ \| | | (__| | | | |_) | (_) | (_) | |_ " >&2
-    echo -e "/_/   \_\_|  \___|_| |_|_.__/ \___/ \___/ \__|_$green$__version__" >&2
-    echo -e "$nc" >&2
+    echo -e "/_/   \_\_|  \___|_| |_|_.__/ \___/ \___/ \__|\
+    _$green$__version__$nc\n" >&2
     echo -e "Welcome in archboot, a script made with love by grm34!" >&2
     echo -e "This script perform an automatic install of Archlinux." >&2
     echo -e "Pretty simple, it only ask you for hostname, username," >&2
@@ -27,25 +27,29 @@ _banner() {
 
 # Function to ask some infos
 _prompt() {
-    echo -e "$yellow" >&2
-    echo -e "==> $green$1 $red$2 $green$3 $red$4 $green$5 $red$6 $green$7 $red$8$nc" >&2
-    echo -e "$yellow==> ---------------------------------------------------$nc" >&2
+    echo -e "$yellow==> $green$1 $red$2 $green$3 \
+    $red$4 $green$5 $red$6 $green$7 $red$8$nc" >&2
+    echo -e "$yellow==> -------------------------\
+    --------------------------$nc" >&2
     echo -ne "$yellow==> $nc" >&2
 }
 
 # Function to ask confirmation (Yes/No)
 _confirm() {
-    until [[ ${confirm} == "y" || ${confirm} == "n" ]]; do
-    echo -e "$yellow\n==> $green$1 $red[y/n]$nc" >&2
-    echo -e "$yellow==> --------------------------------------------------$nc" >&2
-    echo -ne "$yellow==> $nc" >&2
-    read -r confirm
+    until [[ ${confirm} == "y" || ${confirm} == "n" ]]
+    do
+        echo -e "$yellow\n==> $green$1 $red[y/n]$nc" >&2
+        echo -e "$yellow==> -------------------------\
+        -------------------------$nc" >&2
+        echo -ne "$yellow==> $nc" >&2
+        read -r confirm
     done
 }
 
 # Function to display install steps
 _info() {
-    echo -e "$yellow\n==> $cyan$1...$nc"; sleep 2s
+    echo -e "$yellow\n==> $cyan$1...$nc"
+    sleep 2s
 }
 
 # Function to display some notes
@@ -55,8 +59,9 @@ _note() {
 
 # Function to display errors
 _error() {
-    echo -e "$red\nError: $yellow$1$nc" >&2; sleep 5s
-    exit && reboot
+    echo -e "$red\nError: $yellow$1$nc" >&2
+    sleep 5s
+    reboot
 }
 
 # Function to execute actions in chrooted env
@@ -93,7 +98,8 @@ _banner
 
 # Download base sources
 _confirm "Start downloading sources from github?"
-if [[ ${confirm} == "y" ]]; then
+if [[ ${confirm} == "y" ]]
+then
     _info "Downloading sources"
     wget $_url/src/arch/base            # to install ArchLinux Base system
     wget $_url/src/arch/bootloader      # to install Grub2 bootloader
@@ -104,7 +110,8 @@ if [[ ${confirm} == "y" ]]; then
     wget $_url/src/arch/yaourt          # to set pacman.conf & install yaourt
 else
     exit
-fi; unset confirm
+fi
+unset confirm
 
 # Import base sources
 _info "Importing sources"
@@ -115,19 +122,23 @@ source ./partition; source ./user; source ./yaourt
 _user_infos; _logs; _firmware; _partition; _mounting
 
 # Install ArchLinux
-if [ $? -eq 0 ]; then
+if [ $? -eq 0 ]
+then
     _confirm "Do you wish to install ArchLinux now?"
-    if [[ ${confirm} == "y" ]]; then
+    if [[ ${confirm} == "y" ]]
+    then
         (_base; _bootloader; _user_settings; _yaourt) 2>&1 | tee -a "$logfile"
     else
         exit
-    fi; unset confirm
+    fi
+    unset confirm
 else
     _error "partitionning error, system will reboot... Please try again."
 fi
 
 # Desktop Environment
-if [[ ! -z ${desktop+x} ]]; then
+if [[ ! -z ${desktop+x} ]]
+then
 
     # Download desktop sources
     _info "Downloading desktop sources"
@@ -145,7 +156,8 @@ fi
 
 # Logfile path
 _info "Setting logfile path"
-mkdir /mnt/var/log/archboot; cp "$logfile" /mnt/var/log/archboot/
+mkdir /mnt/var/log/archboot
+cp "$logfile" /mnt/var/log/archboot/
 
 # Install notes
 _note "Installation successful!"
@@ -153,8 +165,11 @@ _note "$__appname__ $__version__ by $__author__ - $__license__"
 
 # Reboot
 _confirm "Do you want to reboot your computer now?"
-if [[ ${confirm} == "y" ]]; then
-    umount -R /mnt; reboot
+if [[ ${confirm} == "y" ]]
+then
+    umount -R /mnt
+    reboot
 else
     exit
-fi; unset confirm
+fi
+unset confirm
