update regex + code ident

diff --git a/archboot b/archboot
--- a/archboot
+++ b/archboot
@@ -2,26 +2,31 @@
 __appname__="archboot"
 __version__="v2.7.5"
 __branch__="dev"
-__author__="grm34"
+__author__="@grm34"
 __license__="Apache v2.0 License"
 
 _banner() {
     echo -e "${red}" >&2
-    echo -e "    _             _     _                 _   " >&2
-    echo -e "   / \   _ __  __| |__ | |__   ___   ___ | |_ " >&2
-    echo -e "  / _ \ | '__/ __| '_ \| '_ \ / _ \ / _ \| __|" >&2
-    echo -e " / ___ \| | | (__| | | | |_) | (_) | (_) | |_ " >&2
-    echo -e "/_/   \_\_|  \___|_| |_|_.__/ \___/ \___/ \__|_${green}${__version__}\n" >&2
-    echo -e "${blue}Welcome in archboot, a script made with love by ${__author__}${nc}\n" >&2
+    echo -e "      _             _     _                 _   " >&2
+    echo -e "     / \   _ __  __| |__ | |__   ___   ___ | |_ " >&2
+    echo -e "    / _ \ | '__/ __| '_ \| '_ \ / _ \ / _ \| __|" >&2
+    echo -e "   / ___ \| | | (__| | | | |_) | (_) | (_) | |_ " >&2
+    echo -e "  /_/   \_\_|  \___|_| |_|_.__/ \___/ \___/ \__| \
+${green}${__version__}" >&2
+    echo -e "${blue}" >&2
+    echo -e " Welcome in archboot, a script made with love by \
+${__author__}" >&2
+    echo -e "${nc}" >&2
     echo -e "Arch Linux is a light and fast distribution whose concept" >&2
-    echo -e "is to remain as simple as possible. In the same purpose this" >&2
-    echo -e "script performs minimalist installation, it only installs the" >&2
-    echo -e "required packages, in order to give free choice to the user." >&2
-    echo -e "Pretty simple, it just prompt for hostname,username, password," >&2
-    echo -e "which disk to use, required partitions, language, timezone and" >&2
-    echo -e "if you wish to install a desktop environment. According to the" >&2
-    echo -e "chosen one and in order to get complete support, additionals" >&2
-    echo -e "packages may be required." >&2
+    echo -e "is to remain  as simple as possible.  In the same purpose" >&2
+    echo -e "this script  performs  minimalist  installation,  it only" >&2
+    echo -e "installs  the required  packages,  in order  to give free" >&2
+    echo -e "choice to  the user.  Pretty simple,  it just  prompt for" >&2
+    echo -e "hostname, username, password, which disk to use, required" >&2
+    echo -e "partitions, language, timezone and if you wish to install" >&2
+    echo -e "a desktop  environment.  According to the  chosen one and" >&2
+    echo -e "in order to get  complete  support, additionals  packages" >&2
+    echo -e "may be required." >&2
 }
 
 #
@@ -55,7 +60,7 @@ EOF
 _logs() {
     _info "Setting archboot log"
     datetime=$(date '+%d-%m-%Y')
-    logfile="archboot_${datetime}.log"
+    log="archboot_${datetime}.log"
 }
 
 # Function to set system clock
@@ -71,18 +76,21 @@ _error() {
     echo -e "${red}\n\nError: ${yellow}${1}${nc}\n" >&2
     for d in $(seq 10 -1 1)
     do
-        echo -ne "\r\033[K${green}System will reboot in ${d}s...${nc}" && sleep 1
+        echo -ne "\r\033[K${green}System will reboot in ${d}s...${nc}"
+        sleep 1
     done
-    echo; reboot
+    echo
+    reboot
 }
 
 # Function to ask confirmation (Yes/No)
 _confirm() {
-    until [[ ${confirm} == "y" || ${confirm} == "n" ]]
+    until [[ ${confirm} =~ ^[yn]$ ]]
     do
-        echo -e "${yellow}\n==> ${green}${1} ${red}[y/n]${nc}" >&2
-        echo -e "${yellow}==> -------------------------------------------------------${nc}" >&2
-        echo -ne "${yellow}==> ${nc}" >&2
+        echo -e "${yellow}\n==> ${green}${1} ${red}[y/n]${yellow}" >&2
+        echo -e "==> \
+-------------------------------------------------------" >&2
+        echo -ne "==> ${nc}" >&2
         read -r confirm
     done
 }
@@ -90,13 +98,16 @@ _confirm() {
 # Function to ask some infos
 _prompt() {
     echo -e "${yellow}" >&2
-    echo -e "==> ${green}${1} ${red}${2} ${green}${3} ${red}${4} ${green}${5} ${red}${6} ${green}${7} ${red}${8} ${green}${9} ${red}${10} ${green}${11} ${red}${12}${nc}" >&2
+    echo -e "==> ${green}${1} ${red}${2} ${green}${3} ${red}${4} \
+${green}${5} ${red}${6} ${green}${7} ${red}${8} ${green}${9} \
+${red}${10} ${green}${11} ${red}${12}${yellow}" >&2
     if [[ ! -z ${13+x} ]]
     then
-        echo -e "${yellow}==> ${green}${13} ${red}${14} ${green}${15} ${red}${16} ${green}${17} ${red}${18} ${green}${19} ${red}${20}${nc}" >&2
+        echo -e "==> ${green}${13} ${red}${14} ${green}${15} ${red}${16} \
+${green}${17} ${red}${18} ${green}${19} ${red}${20}${yellow}" >&2
     fi
-    echo -e "${yellow}==> -------------------------------------------------------${nc}" >&2
-    echo -ne "${yellow}==> ${nc}" >&2
+    echo -e "==> -------------------------------------------------------" >&2
+    echo -ne "==> ${nc}" >&2
 }
 
 #
@@ -124,7 +135,8 @@ if [[ $? == 0 ]]
 then
     _note "OK, you are connected to Internet."
 else
-    _error "you are not connected to Internet. Please check if ethernet is plugged in."
+    _error "you are not connected to Internet. \
+Please check if ethernet is plugged in."
 fi
 
 # Download base sources
@@ -168,7 +180,7 @@ then
     _confirm "Do you wish to install ArchLinux now?"
     if [[ ${confirm} == "y" ]]
     then
-        (_base; _bootloader) 2>&1 | tee -a "${logfile}"
+        (_base; _bootloader) 2>&1 | tee -a "${log}"
     else
         _error "aborted by user! Please try again."
     fi
@@ -189,7 +201,7 @@ then
         source ./desktop; source ./display; source ./desktop_apps
 
         # Install desktop environment
-        (_install_DE; _display_manager; _DE_settings) 2>&1 | tee -a "${logfile}"
+        (_install_DE; _display_manager; _DE_settings) 2>&1 | tee -a "${log}"
     fi
 
     # Logfile path
@@ -198,7 +210,8 @@ then
     cp "${logfile}" /mnt/var/log/archboot/
 
     # Success notes
-    _note "Installation successful! ${__appname__} ${__version__} by ${__author__} under ${__license__}"
+    _note "Installation successful! \
+${__appname__} ${__version__} by ${__author__} under ${__license__}"
 
     # Reboot
     _confirm "Do you want to reboot your computer now?"
@@ -206,7 +219,8 @@ then
     then
         umount -R /mnt; reboot
     else
-        echo; exit
+        echo
+        exit
     fi
 
 else
